all: attack01 attack02 attack03 attack04

attack01: attack01.c
	gcc -o attack01 attack01.c -lcrypto

attack02: attack02.c
	gcc -o attack02 attack02.c -lcrypto

attack03: attack03.c
	gcc -o attack03 attack03.c -lcrypto

attack04: attack04.c
	gcc -o attack04 attack04.c -lcrypto

clean:
	rm -f attack01 attack02 attack03 attack04
