########################################
#
# Makefile for Homework 02
#
# WARNING - DO NOT CHANGE THIS FILE
#
#
########################################

default: attack02 attack03 attack04 attack05 attack06 attack07 attack08 attack09 attack10

attack02: attack02.c
	gcc -o attack02 attack02.c

attack03: attack03.c
	gcc -o attack03 attack03.c

attack04: attack04.c
	gcc -o attack04 attack04.c

attack05: attack05.c
	gcc -o attack05 attack05.c

attack06: attack06.c
	gcc -o attack06 attack06.c

attack07: attack07.s
	gcc -o attack07 attack07.s

attack08: attack08.c
	gcc -o attack08 attack08.c

attack09: attack09.c
	gcc -o attack09 attack09.c

attack10: attack10.c
	gcc -o attack10 attack10.c

