########################################
#
# Makefile for Homework 03
#
# WARNING - DO NOT CHANGE THIS FILE
#
#
########################################

default: attack01 attack02 attack03 attack04 attack05 attack06

attack01: attack01.c
	gcc -o attack01 attack01.c

attack02: attack02.c
	gcc -o attack02 attack02.c

attack03: attack03.c
	gcc -o attack03 attack03.c

attack04: attack04.c
	gcc -o attack04 attack04.c

attack05: attack05.c
	gcc -o attack05 attack05.c

attack06: attack06.c
	gcc -o attack06 attack06.c
